### ISSUE TITLE
Avoiding cleanup of nuget packages during build

### ISSUE THREAD

**Issue by AwaNoodle** [lholman/OneBuild#32]
Atm we are not checking in OneBuild into source control, instead pulling it down as a initial step in TeamCity. This step pulls down all of the packages in the solution, including OneBuild. Once of the steps then removes all of the packages and pulls them back down again, duplicating effort in our current flow.

Is it possible to have the clean up behavior for the packages switchable to avoid the two passes? 

I acknowledge that this reduces the flow where you build from an initial pull down from source to a devs machine. Atm we don't want to check in all of the dependencies if possible.

**Comment by lholman** [comment]
Nice observation and I understand the requirement, however, the main goal of OneBuild is to give the same build experience both locally as within your CI tool of choice. This means the use of a separate step in your CI server to do package restore prior to running OneBuild should not be required and indeed I would discourage, I'd challenge you to make that change and see if it works for you. The obvious single change being that you will need to add OneBuild and dependent packages to source control, necessity, otherwise it's a chicken and egg situation. Maybe the documentation isn't clear around this?

**Comment by lholman** [comment]
@AwaNoodle Am I ok to close this for now or is there anything I've missed?
